### ISSUE TITLE
请问怎么初始化SDK 配置APk

### ISSUE THREAD

**Issue by lenglengtaidu** [JimiPlatform/react-native-baidu-map-jm#4]

**Comment by CLANNADAIR** [comment]
RN版本在0.60之下，直接调用下面指令关联：

```
$ react-native link react-native-baidu-map-jm
```

 初始化配置AndroidManifest.xml文件

1. 在<application>中加入如下代码配置开发密钥（AK）：

```
<application>  
    <meta-data  
        android:name="com.baidu.lbsapi.API_KEY"  
        android:value="开发者 key" />  
</application>
```

2.  在<application/>外部添加如下权限声明：

```
<!-- 访问网络，进行地图相关业务数据请求，包括地图数据，路线规划，POI检索等 -->
<uses-permission android:name="android.permission.INTERNET" />
<!-- 获取网络状态，根据网络状态切换进行数据请求网络转换 -->
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    
<!-- 读取外置存储。如果开发者使用了so动态加载功能并且把so文件放在了外置存储区域，则需要申请该权限，否则不需要 -->
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<!-- 写外置存储。如果开发者使用了离线地图，并且数据写在外置存储区域，则需要申请该权限 -->
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

**注：自Android6.0起部分权限的使用需要开发者在代码中动态申请**

**Comment by lenglengtaidu** [comment]
![微信图片_20200727145907](https://user-images.githubusercontent.com/46698833/88512832-c40a7180-d019-11ea-8326-16bf39466ecb.png)
感谢你的回复！
请问这是什么错误？

**Comment by Eafy** [comment]
关闭下面图中红框上部分的Module依赖，打开下面的本地地图lib依赖：
![B7A8432A-C585-4EE7-A627-BBFC4BE04AFD](https://user-images.githubusercontent.com/12604160/88513156-5c085b00-d01a-11ea-8cf4-899b9739539e.png)

**Comment by lenglengtaidu** [comment]
![image](https://user-images.githubusercontent.com/46698833/88514215-42681300-d01c-11ea-884f-e772ea0b689e.png)
请问是在这个位置吗？ react-native 版本 0.62.2 
加了还是报错
![image](https://user-images.githubusercontent.com/46698833/88514366-8b1fcc00-d01c-11ea-9d2f-f2738c0c3c46.png)

**Comment by lenglengtaidu** [comment]
大佬 MapListener.java 打开是乱码

**Comment by lenglengtaidu** [comment]
java 文件打不开

**Comment by lenglengtaidu** [comment]
![image](https://user-images.githubusercontent.com/46698833/88522023-63cefc00-d028-11ea-9251-0638f8379440.png)
大佬，这个文件好像有点问题

**Comment by Eafy** [comment]
请稍等，过会会重新更新下。
